-- 1. Таблица товаров (Products)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    price INTEGER NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    full_description TEXT,
    img TEXT,
    animal_types TEXT[] NOT NULL,
    is_featured BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'available' CHECK (status IN ('available', 'preorder', 'out_of_stock')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Таблица заказов (Orders)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    items JSONB NOT NULL, -- Массив товаров в заказе
    total INTEGER NOT NULL,
    user_id UUID REFERENCES auth.users(id), -- Optional: Associate with registered user
    status TEXT DEFAULT 'new' CHECK (status IN ('new', 'completed', 'cancelled')),
    date TEXT, -- Сохраняем как текст или TIMESTAMP
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Таблица блога (Blog Posts)
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    excerpt TEXT,
    content TEXT NOT NULL,
    date TEXT,
    image_url TEXT,
    slug TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Включаем RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- Политики доступа
-- Публичный просмотр товаров
CREATE POLICY "Enable read access for all users" ON public.products FOR SELECT USING (true);
-- Публичный просмотр блога
CREATE POLICY "Enable read access for all users" ON public.blog_posts FOR SELECT USING (true);
-- Публичное создание заказов (для гостей и пользователей)
CREATE POLICY "Enable insert for all users" ON public.orders FOR INSERT WITH CHECK (true);
-- Пользователи могут видеть свои собственные заказы
CREATE POLICY "Users can see their own orders" ON public.orders FOR SELECT USING (user_id = auth.uid());

-- 4. Начальные данные (Seed Data)
-- Используйте этот блок, если хотите сразу наполнить базу через SQL Editor
INSERT INTO public.products (article, name, price, category, description, full_description, img, animal_types, is_featured, status)
VALUES 
('D-001', 'Корм Royal Canin Veterinary Diet Gastrointestinal 2кг', 9500, 'food', 'Диетический корм при нарушениях пищеварения.', 'Полнорационный диетический сухой корм для взрослых собак.', 'https://images.unsplash.com/photo-1589924691106-073b61073860?q=80&w=800&h=800&auto=format&fit=crop', ARRAY['dogs'], true, 'available'),
('D-002', 'Frontline Combo для собак 10-20кг (3 пипетки)', 7800, 'medicines', 'Капли от блох и клещей.', 'Инсектоакарицидный раствор для наружного применения.', 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?q=80&w=800&h=800&auto=format&fit=crop', ARRAY['dogs'], false, 'available'),
('D-005', 'Бравекто для собак 10-20кг (1 табл)', 18500, 'medicines', 'Защита от блох и клещей на 12 недель.', 'Жевательная таблетка для системной защиты.', 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?q=80&w=800&h=800&auto=format&fit=crop', ARRAY['dogs'], true, 'available'),
('C-001', 'GRANDORF Cat 4 Meat & Brown Rice 2кг', 9200, 'food', 'Низкозерновой корм для стерилизованных кошек.', 'Бельгийский корм супер-премиум класса.', 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=800&h=800&auto=format&fit=crop', ARRAY['cats'], true, 'available'),
('H-001', 'Гель Alezan охлаждающе-разогревающий 500мл', 5200, 'medicines', 'Средство для суставов и мышц.', 'Применяется при миозитах и синовитах.', 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?q=80&w=800&h=800&auto=format&fit=crop', ARRAY['horses'], true, 'available'),
('D-003', 'Шампунь 8in1 Tea Tree Oil 250мл', 3200, 'hygiene', 'Успокаивающий шампунь с маслом чайного дерева.', 'Снимает раздражение и зуд.', 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=800&h=800&auto=format&fit=crop', ARRAY['dogs'], false, 'available'),
('C-002', 'Наполнитель TOFU Mr.Fresh 6л', 4500, 'hygiene', 'Натуральный соевый наполнитель.', 'Можно смывать в унитаз.', 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?q=80&w=800&h=800&auto=format&fit=crop', ARRAY['cats'], false, 'available'),
('S-001', 'Корм RIO для волнистых попугаев 1кг', 1950, 'food', 'Основной рацион для птиц.', 'Сбалансированная зерносмесь.', 'https://images.unsplash.com/photo-1522850935371-49c059385653?q=80&w=800&h=800&auto=format&fit=crop', ARRAY['birds'], false, 'available'),
('E-001', 'Термометр ветеринарный Microlife', 4500, 'equipment', 'Точное измерение за 10 секунд.', 'Гибкий кончик, водонепроницаемый.', 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?q=80&w=800&h=800&auto=format&fit=crop', ARRAY['all'], false, 'available'),
('V-001', 'Гамавит 10мл', 2800, 'medicines', 'Иммуностимулятор и детоксикант.', 'Повышает устойчивость к заболеваниям.', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=800&h=800&auto=format&fit=crop', ARRAY['all'], false, 'available')
ON CONFLICT (article) DO NOTHING;
