-- 1. Таблица товаров (Products)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    price INTEGER NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    full_description TEXT,
    img TEXT,
    animal_types TEXT[] NOT NULL,
    is_featured BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'available' CHECK (status IN ('available', 'preorder', 'out_of_stock')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Таблица заказов (Orders)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    items JSONB NOT NULL, -- Массив товаров в заказе
    total INTEGER NOT NULL,
    status TEXT DEFAULT 'new' CHECK (status IN ('new', 'completed', 'cancelled')),
    date TEXT, -- Сохраняем как текст или TIMESTAMP
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Таблица блога (Blog Posts)
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    excerpt TEXT,
    content TEXT NOT NULL,
    date TEXT,
    image_url TEXT,
    slug TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Включаем RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- Политики доступа
-- Публичный просмотр товаров
CREATE POLICY "Enable read access for all users" ON public.products FOR SELECT USING (true);
-- Публичный просмотр блога
CREATE POLICY "Enable read access for all users" ON public.blog_posts FOR SELECT USING (true);
-- Публичное создание заказов
CREATE POLICY "Enable insert for all users" ON public.orders FOR INSERT WITH CHECK (true);

-- (Внимание: Для админ-операций через Backend рекомендуется использовать Service Role Key, 
-- который обходит RLS, поэтому специфические политики для INSERT/UPDATE в товарах не обязательны, 
-- либо добавьте политики на основе auth.uid() если используете Supabase Auth)
